apiVersion: 1

datasources:
  - name: PostgreSQL_KursEur
    type: grafana-postgresql-datasource
    access: proxy
    url: postgres_kurs_eur:5432
    database: kurs_eur_db
    user: kursadmin
    secureJsonData:
      password: "kursadmin"
    jsonData:
      sslmode: "disable"
      maxOpenConns: 10
      maxIdleConns: 2
      connMaxLifetime: 14400
      postgresVersion: 1500
      timescaledb: false
    isDefault: true
    editable: true
